runner:
  n_epochs: -1
  total_steps: 51
  gradient_clipping: 5.0
  gradient_accumulate_steps: 3

  log_step: 50
  # save_step: 10000
  save_step: 50
  max_keep: 10

  fp16: true

  # ADD  #
  multi_agent:
    rounds: 2
    round_hours: 1
    round_sample_rate: 0.6
    criteria: consine_similarity
  # ADD~ #

optimizer:
  name: AdamW_with_schedule
  lr: 2.e-4
  warmup_proportion: 0.07
  betas: [0.9, 0.98]
  eps: 1.e-6
  weight_decay: 1.e-6

pretrain_expert:
  datarc:
    num_workers: 24
    train_batch_size: 8
    max_timestep: 0

    # MODIFY  #
    libri_root: ~ # set to None -> use file_path
    metadata_prefix: /work/twsmpkh238/modelSteal/s3prl/s3prl/data/csv
    sets: ['aishell'] # you can set ['wsj', 'libri']
    # MODIFY~ #
